// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogbzhbwfucgjiafhsxab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nYnpoYndmdWNnamlhZmhzeGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjMxMzAsImV4cCI6MjA3MzMzOTEzMH0.DocOgMUIvR1V22WSAShP7c9D7Fc66i_YPLkM0AMDvYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});